# Generated by Django 3.2.24 on 2024-03-27 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Miejscowość')),
                ('street', models.CharField(max_length=255, verbose_name='Ulica')),
                ('district', models.CharField(max_length=255, verbose_name='Powiat')),
                ('commune', models.CharField(max_length=255, verbose_name='Gmina')),
                ('house_number', models.CharField(max_length=255, verbose_name='Numer domu')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_string_RSPO', models.CharField(blank=True, default='RSPO', max_length=255, null=True, verbose_name='RSPO')),
                ('csv_string_nip', models.CharField(blank=True, default='nip', max_length=255, null=True, verbose_name='NIP')),
                ('csv_string_school_name', models.CharField(blank=True, default='Nazwa szkoły', max_length=255, null=True, verbose_name='Nazwa szkoły')),
                ('csv_string_phone', models.CharField(blank=True, default='tel.', max_length=255, null=True, verbose_name='Telefon kontaktowy szkoły')),
                ('csv_string_email', models.CharField(blank=True, default='email', max_length=255, null=True, verbose_name='Szkolny kontaktowy adres e-mail')),
                ('csv_string_total_students', models.CharField(blank=True, default='suma', max_length=255, null=True, verbose_name='Uczniów')),
                ('csv_string_director_first_name', models.CharField(blank=True, default='Imię dyr.', max_length=255, null=True, verbose_name='Dyrektor imię')),
                ('csv_string_director_last_name', models.CharField(blank=True, default='Nazwisko dyr.', max_length=255, null=True, verbose_name='Dyrektor nazwisko')),
                ('csv_string_city', models.CharField(blank=True, default='Miejscowość', max_length=255, null=True, verbose_name='Miejscowość')),
                ('csv_string_street', models.CharField(blank=True, default='Ulica', max_length=255, null=True, verbose_name='Ulica')),
                ('csv_string_house_number', models.CharField(blank=True, default='Numer domu', max_length=10, null=True, verbose_name='Numer domu')),
                ('csv_string_district', models.CharField(blank=True, default='Powiat', max_length=255, null=True, verbose_name='Powiat')),
                ('csv_string_commune', models.CharField(blank=True, default='Gmina', max_length=255, null=True, verbose_name='Gmina')),
                ('pdf_protocol_logo', models.ImageField(blank=True, null=True, upload_to='public/uploads/', verbose_name='Czcionka protokołu PDF')),
                ('pdf_protocol_font', models.FileField(blank=True, null=True, upload_to='public/uploads/', verbose_name='Logo protokołu PDF')),
            ],
            options={
                'verbose_name': 'Ustawienie',
                'verbose_name_plural': 'Ustawienia',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSPO', models.IntegerField(unique=True, verbose_name='RSPO')),
                ('nip', models.BigIntegerField(verbose_name='NIP')),
                ('school_name', models.CharField(max_length=255, verbose_name='Nazwa szkoły')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon kontaktowy szkoły')),
                ('email', models.EmailField(max_length=254, verbose_name='Szkolny kontaktowy adres e-mail')),
                ('director_first_name', models.CharField(max_length=255, verbose_name='Dyrektor imię')),
                ('director_last_name', models.CharField(max_length=255, verbose_name='Dyrektor nazwisko')),
                ('total_students', models.IntegerField(verbose_name='Uczniów')),
                ('goods_received', models.BooleanField(blank=True, default=False, null=True, verbose_name='Otrzymane towary')),
                ('acceptance_protocol', models.FileField(blank=True, null=True, upload_to='', verbose_name='Protokół odbioru')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_schools', to='common.address', verbose_name='Adres')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='directed_schools', to=settings.AUTH_USER_MODEL, verbose_name='Dyrektor')),
            ],
            options={
                'verbose_name': 'Szkoła',
                'verbose_name_plural': 'Szkoły',
            },
        ),
    ]
