# Generated by Django 5.0.2 on 2024-05-03 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa sprzętu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis sprzętu')),
            ],
            options={
                'verbose_name': 'Typ sprzętu',
                'verbose_name_plural': 'Typy sprzętu',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numer seryjny')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notatki')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='common.equipmenttype', verbose_name='Typ sprzętu')),
            ],
            options={
                'verbose_name': 'Sprzęt',
                'verbose_name_plural': 'Sprzęty',
            },
        ),
        migrations.CreateModel(
            name='SchoolEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ilość')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_equipment', to='common.equipment', verbose_name='Sprzęt')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_equipment', to='common.school', verbose_name='Szkoła')),
            ],
            options={
                'verbose_name': 'Sprzęt szkolny',
                'verbose_name_plural': 'Sprzęt szkolny',
            },
        ),
    ]
