# Generated by Django 5.0.4 on 2024-05-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_equipmenttype_equipment_schoolequipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adres', 'verbose_name_plural': 'Adresy'},
        ),
    ]
