# Generated by Django 5.0.4 on 2024-06-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_address_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis sprzętu'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='nieznany sprzet', max_length=255, verbose_name='Nazwa sprzętu'),
        ),
        migrations.AddField(
            model_name='school',
            name='equipment',
            field=models.ManyToManyField(through='common.SchoolEquipment', to='common.equipment', verbose_name='Sprzęt'),
        ),
        migrations.AddField(
            model_name='schoolequipment',
            name='serial_numbers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numery seryjne'),
        ),
        migrations.DeleteModel(
            name='EquipmentType',
        ),
    ]
