# Generated by Django 5.0.4 on 2024-06-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_equipment_equipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa sprzętu'),
        ),
    ]
