# Generated by Django 5.0.4 on 2024-06-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='pdf_protocol_font',
            field=models.FileField(blank=True, null=True, upload_to='public/uploads/', verbose_name='Czcionka protokołu PDF'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pdf_protocol_logo',
            field=models.ImageField(blank=True, null=True, upload_to='public/uploads/', verbose_name='Logo protokołu PDF'),
        ),
    ]
